[package]
name = "myos"
version = "0.1.0"
authors = ["heaven0sky <286076057@qq.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

